server:
  port: 9999
spring:
  profiles: dev
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    #Eureka 剔除失效服务
    lease-renewal-interval-in-seconds: 10 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    eureka.instance.lease-expiration-duration-in-seconds: 5 #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    status-page-url: http://localhost:${server.port}/swagger-ui.html #Swagger2整合Eureka，实现Eureka页面自动跳转到Swagger2UI界面查看服务接口信息

---
server:
  port: 9998
spring:
  profiles: test
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    #Eureka 剔除失效服务
    lease-renewal-interval-in-seconds: 10 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    eureka.instance.lease-expiration-duration-in-seconds: 5 #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    status-page-url: http://localhost:${server.port}/swagger-ui.html #Swagger2整合Eureka，实现Eureka页面自动跳转到Swagger2UI界面查看服务接口信息